# Generated by Django 4.0.5 on 2022-07-01 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('country', models.CharField(max_length=255)),
                ('coach', models.CharField(max_length=255)),
                ('information', models.TextField(blank=True)),
                ('logo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True)),
                ('information', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='players.team')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
                'ordering': ['nickname'],
            },
        ),
    ]
